[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Environment variables for content management
[context.production.environment]
  TWOFIFTHS_GOOGLE_DRIVE_FILE_ID = "1gAlt0FsIcspWAJ67D69h0ENATCymZiW9"
  TWOFIFTHS_CONTENT_CHECK_INTERVAL = "30000"

# Redirect rules
[[redirects]]
  from = "/admin"
  to = "/admin-panel-x7k9/"
  status = 301

[[redirects]]
  from = "/cms"
  to = "/admin-panel-x7k9/"
  status = 301