[build]
  command = "npm run build"
  publish = "dist"
  
# Ignore admin panel from build
[build.ignore]
  command = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF admin-panel-x7k9/"

[build.environment]
  NODE_VERSION = "18"

# Environment variables for content management
[context.production.environment]
  TWOFIFTHS_GOOGLE_DRIVE_FILE_ID = "1gAlt0FsIcspWAJ67D69h0ENATCymZiW9"
  TWOFIFTHS_CONTENT_CHECK_INTERVAL = "30000"

# Redirect rules
[[redirects]]
  from = "/admin"
  to = "/admin-panel-x7k9/"
  status = 301

[[redirects]]
  from = "/cms"
  to = "/admin-panel-x7k9/"
  status = 301

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200